# Generated by Django 4.2 on 2023-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureSoftware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='name',
        ),
        migrations.AlterField(
            model_name='software',
            name='public_key',
            field=models.TextField(),
        ),
    ]
